SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE IF EXISTS product;
TRUNCATE TABLE IF EXISTS product_type;
TRUNCATE TABLE IF EXISTS product_income;
TRUNCATE TABLE IF EXISTS product_outcome;
TRUNCATE TABLE IF EXISTS supplier;
TRUNCATE TABLE IF EXISTS user;
SET REFERENTIAL_INTEGRITY TRUE;