SET REFERENTIAL_INTEGRITY FALSE;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS product_type;
DROP TABLE IF EXISTS product_income;
DROP TABLE IF EXISTS product_outcome;
DROP TABLE IF EXISTS supplier;
DROP TABLE IF EXISTS user;
SET REFERENTIAL_INTEGRITY TRUE;